name: Changelog

on:
  pull_request:
#    types: [ "opened" ]

jobs:
  add-changelog:
    name: Add changelog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: actions/checkout@v3
      if: github.event_name == 'push'
      with:
        fetch-depth: 0

    - name: Add changelog file
      id: add
      run: |
        git branch
        bin/changelog add -f ${{ github.event.pull_request.number }} -m "${{ github.event.pull_request.title }}" -t fixed --pr ${{ github.event.pull_request.number }}
        echo "::set-output name=filename::${{ github.event.pull_request.number }}.yaml"
        
        git config --local user.email "$(git log -n 1 --pretty=format:%ae)"
        git add CHANGELOG/unreleased/${{ github.event.number }}.yaml
        git commit -m "Add changelog file CHANGELOG/unreleased/${{ github.event.number }}.yaml"
        git push

    - name: debug
      run: echo '${{ toJson(github.event) }}'

    - name: Add a comment
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'I created a changelog YAML for you.'
          })
          
